#!/usr/bin/env python3
"""Generate the Compose .env file from config.json.

Compose natively reads `.env` from the project directory for variable
substitution in docker-compose.yml. We keep config.json as the single
source of truth for the whole tool and project only the fields Compose
needs into the .env file.

Usage:
    python scripts/sync_compose_env.py
    python scripts/sync_compose_env.py --config path/to/config.json --env path/to/.env
    python scripts/sync_compose_env.py --check    # exit 1 if .env is stale

Designed to be safe to run repeatedly: it overwrites .env atomically and
emits a header warning humans not to edit it by hand.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

# Fields that this script projects from config.json into the .env file.
# Each entry: (env_var_name, json_path, default, validator)
# json_path is a tuple of keys to traverse.

_ENV_HEADER = """# AUTO-GENERATED by scripts/sync_compose_env.py from config.json.
# DO NOT EDIT BY HAND — your changes will be overwritten.
# To change these values, edit config.json and re-run the sync script.
"""


def _get(cfg: dict, path: tuple[str, ...], default: Any = None) -> Any:
    """Walk a nested dict by key path, returning `default` if any key is missing."""
    cur: Any = cfg
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    return cur


def _require(cfg: dict, path: tuple[str, ...]) -> Any:
    """Like _get but raises if missing."""
    sentinel = object()
    value = _get(cfg, path, sentinel)
    if value is sentinel:
        dotted = ".".join(path)
        raise ValueError(f"config.json is missing required field: {dotted}")
    return value


def _parse_base_url(base_url: str) -> tuple[str, int]:
    """Extract (host, port) from an http(s)://host:port URL.

    Falls back to port 11434 if not specified, matching Ollama's default.
    """
    parsed = urlparse(base_url)
    if parsed.scheme not in ("http", "https"):
        raise ValueError(
            f"llm.base_url must start with http:// or https:// (got {base_url!r})"
        )
    if not parsed.hostname:
        raise ValueError(f"llm.base_url has no hostname (got {base_url!r})")
    port = parsed.port if parsed.port is not None else 11434
    return parsed.hostname, port


def build_env(cfg: dict) -> dict[str, str]:
    """Build the dict of env vars to write to .env from config.json.

    Validates that required fields are present and have sensible values.
    Only Ollama is supported here — other providers don't need a local
    container, so this script is a no-op for them (returns empty dict).
    """
    provider = _get(cfg, ("llm", "provider"), "ollama")
    if provider != "ollama":
        # Non-local provider (OpenAI, Anthropic, TELUS GenAI, etc.) — no
        # Compose stack needed. Caller can decide whether to skip writing
        # the file entirely.
        return {}

    base_url = _require(cfg, ("llm", "base_url"))
    host, port = _parse_base_url(base_url)

    model = _require(cfg, ("llm", "model"))
    if not isinstance(model, str) or not model.strip():
        raise ValueError("llm.model must be a non-empty string")

    env: dict[str, str] = {
        "COMPOSE_PROJECT_NAME": str(_get(cfg, ("project_name",), "doc-gen")),
        "OLLAMA_IMAGE": str(_get(cfg, ("docker", "image"), "ollama/ollama:latest")),
        "OLLAMA_BIND_ADDR": host,
        "OLLAMA_PORT": str(port),
        "OLLAMA_MODEL": model,
        "OLLAMA_KEEP_ALIVE": str(_get(cfg, ("llm", "keep_alive"), "-1")),
        "OLLAMA_NUM_PARALLEL": str(_get(cfg, ("llm", "num_parallel"), 1)),
        "OLLAMA_CONTEXT_LENGTH": str(_get(cfg, ("llm", "context_length"), 8192)),
        "OLLAMA_MAX_LOADED_MODELS": str(_get(cfg, ("llm", "max_loaded_models"), 1)),
    }

    # Sanity-check numeric values.
    for key in ("OLLAMA_PORT", "OLLAMA_NUM_PARALLEL", "OLLAMA_CONTEXT_LENGTH",
                "OLLAMA_MAX_LOADED_MODELS"):
        try:
            n = int(env[key])
        except ValueError:
            raise ValueError(f"{key} must be an integer (got {env[key]!r})")
        if n < 1:
            raise ValueError(f"{key} must be >= 1 (got {n})")

    return env


def render_env_file(env: dict[str, str]) -> str:
    """Render the env dict to the textual contents of a .env file."""
    lines = [_ENV_HEADER]
    for key, value in env.items():
        # Compose's .env parser is simple: KEY=VALUE, no shell expansion.
        # Quote values that contain whitespace or special chars to be safe.
        if any(c in value for c in (" ", "\t", "#", "\"", "'")):
            # Escape backslashes and double-quotes, then wrap in double quotes.
            escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
            lines.append(f'{key}="{escaped}"')
        else:
            lines.append(f"{key}={value}")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def atomic_write(path: Path, contents: str) -> None:
    """Write `contents` to `path` atomically (write to tmp, then rename)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(
        prefix=".env.", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(contents)
        os.replace(tmp_path, path)
    except Exception:
        # Clean up tmp file on failure.
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Compose .env from config.json."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("config.json"),
        help="Path to config.json (default: ./config.json).",
    )
    parser.add_argument(
        "--env",
        type=Path,
        default=Path(".env"),
        help="Path to the .env file to write (default: ./.env).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write; exit 1 if .env is missing or stale. "
             "Useful in CI to ensure the .env was regenerated after a "
             "config change.",
    )
    args = parser.parse_args(argv)

    if not args.config.is_file():
        print(f"error: config file not found: {args.config}", file=sys.stderr)
        return 2

    try:
        cfg = json.loads(args.config.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"error: {args.config} is not valid JSON: {e}", file=sys.stderr)
        return 2

    try:
        env = build_env(cfg)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    if not env:
        print(
            f"llm.provider is not 'ollama' — no Compose env needed. "
            f"Skipping.",
            file=sys.stderr,
        )
        return 0

    new_contents = render_env_file(env)

    if args.check:
        if not args.env.is_file():
            print(
                f"error: {args.env} does not exist — run without --check "
                f"to generate it.",
                file=sys.stderr,
            )
            return 1
        current = args.env.read_text(encoding="utf-8")
        if current != new_contents:
            print(
                f"error: {args.env} is out of sync with {args.config}. "
                f"Run scripts/sync_compose_env.py to regenerate.",
                file=sys.stderr,
            )
            return 1
        print(f"{args.env} is up to date.")
        return 0

    atomic_write(args.env, new_contents)
    print(f"wrote {args.env} ({len(env)} variables) from {args.config}")
    return 0


if __name__ == "__main__":
    sys.exit(main())